# Generated by Django 3.0.7 on 2020-06-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='user_id',
            new_name='signup_id',
        ),
    ]
