# Generated by Django 3.0.7 on 2020-06-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20200614_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='signup_id',
            new_name='new_id',
        ),
    ]
